### ISSUE TITLE
Cannot install

### ISSUE THREAD

**Issue by apsuhos** [pixelandtonic/HappyLager#11]
![untitled-1](https://cloud.githubusercontent.com/assets/2563197/22782678/f39a144c-eed0-11e6-8646-7b04d1c9cdfa.jpg)
I get this error message after I import the provided sql. After that  happylager.dev/admin directs me to the installation process (not the login page) and the installation fails (oops screen) 

I cannot figure out what I am doing wrong. I use windows 8.1 x64.

**Comment by takobell** [comment]
You get that error after import or during? What are you using to do the import with?

**Comment by apsuhos** [comment]
http://localhost/phpmyadmin/ ---> Create new database (happylager) ---> import (happylager.sql) -----> go > and I get this:

![untitled-1](https://cloud.githubusercontent.com/assets/2563197/22796717/1fc15da4-ef04-11e6-8d1f-b8a406db894c.jpg)

I don't know if it is during the import or after. How can you tell?

**Comment by takobell** [comment]
I'd guess it's a bug in the version of phpMyAdmin you're using.  Can you try importing using a MySQL client app like https://www.sequelpro.com/?

**Comment by apsuhos** [comment]
It was associated with my phpMyAdmin version (4.5.5.1). I upgraded to the last version and it worked fine.

**Comment by takobell** [comment]
Glad you're all sorted!
