### ISSUE TITLE
The new V3 has no /app folder?

### ISSUE THREAD

**Issue by tmikaeld** [pixelandtonic/HappyLager#15]
I'm guessing this demo isn't for V3?

**Comment by angrybrad** [comment]
Not yet... we should have the v3 port of HappyLager done in a week or two.

**Comment by DanielTamkin** [comment]
**_18 days later_**...

Any idea when the V3 port will be done?

**Comment by tmikaeld** [comment]
I understand you have other priorities, but for newcomers to Craft like myself, not having a working demo-site is very disencouraging.
