### ISSUE TITLE
Version 2 or 3?

### ISSUE THREAD

**Issue by akolbo** [pixelandtonic/HappyLager#17]
It'd be helpful for brand new users of craft to know that Happy Lager works with Version 2. This was a hang up for me :)

**Comment by angrybrad** [comment]
Agree... currently it's V2, but it's on our short-list to get the V3 port finished. Sorry for the confusion.

**Comment by j-greig** [comment]
Agreed, this is now an issue for a lot of Craft resources/plugins.
I wish I'd known about the existence of this repo when I was learning Craft 2 :)

**Comment by akolbo** [comment]
@angrybrad, why not add an explanation that Happy Lager runs on  V2  in the repository description/readme file?

**Comment by nettum** [comment]
I agree.
Add a note about it in the [README.md](https://github.com/pixelandtonic/HappyLager/blob/master/README.md) or at least remove the demo-link from the menu on https://craftcms.com/ as the frontpage is heavily craft3 branded.

**Comment by brandonkelly** [comment]
Happy to report that the demo is finally running on Craft 3.

**Comment by nettum** [comment]
I did a clone and setup the project now. Works fine, but needed to set `web/assets/*` as writeable for PHP to get images to work.
