### ISSUE TITLE
CSS Styles are calling

### ISSUE THREAD

**Issue by neni1006** [pixelandtonic/HappyLager#3]
Hello,

This is the which I have installed Craft http://trendsetup.in/ ..

I have not understood this 7th point of Installation Procedure "Create a new virtual host with the hostname happylager.dev that points to the happylager/public/ folder."

Please clear this issue.. Thanks..

**Comment by eyoung100** [comment]
Modify your Servers hosts file to point the IP Address 127.0.0.1  to happylager.dev, and move the contents of public into the web servers folder.
