### ISSUE TITLE
Images not loading

### ISSUE THREAD

**Issue by knynkwl** [pixelandtonic/HappyLager#4]
I am having a problem where the images are not loading. Is this a permission problem?

![screen shot 2015-05-27 at 9 54 11 am](https://cloud.githubusercontent.com/assets/4225771/7842196/7a6abee8-0456-11e5-84a7-73de0093d59c.png)

**Comment by knynkwl** [comment]
It looks like it was a permissions problem. I did `chmod 777 assets/site` and most images started showing up. Now it looks like the only thing missing are the "Our People" sections.

**Comment by dpkonofa** [comment]
Also had the same issue.  Setting the permissions on assets/site worked for me.  I wonder if there should be a note inline with the other permissions that says you need write access to assets/site too.

**Comment by eyoung100** [comment]
I agree there needs to be a note in the Readme.md.  See http://craftcms.stackexchange.com/questions/11400/having-trouble-with-happylager for the fix.
