### ISSUE TITLE
"htaccess" not ".htaccess"

### ISSUE THREAD

**Issue by ncerminara** [pixelandtonic/HappyLager#6]
This URL (from the download button) has an incorrectly named .htaccess file in the public folder.

http://download.buildwithcraft.com/craft/2.4/2.4.2693/Craft-2.4.2693.zip

Which isn't current to GitHub?

**Comment by brandonkelly** [comment]
That download URL is for Craft itself, not the Happy Lager demo site.

In any case, we realize that the filename is “htaccess” and not “.htaccess” - if we included the dot, you wouldn’t be able to see it on Unix/Linux-based systems, which would prevent you from being able to upload it. Part of [Step 1](http://buildwithcraft.com/docs/installing#step-1-upload-the-files) in the installation instructions has you rename it to “.htaccess”:

> * **htaccess** – This file configures Apache servers to direct all traffic hitting your site to that index.php file, without actually needing to include “index.php” in the URLs. Note that it must be renamed to .htaccess for it to actually work. (See “[How do I remove “index.php” from my URLs?](http://buildwithcraft.com/help/remove-index.php)” for more info.)

**Comment by ncerminara** [comment]
Ah - missed that in the docs
